version: "3"

services:
  app:
    container_name: ep7-app-backend
    build: ./docker/api
    volumes:
      - ./api:/ep7-app
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true

  web:
    container_name: ep7-app-frontend
    build: ./docker/web
    volumes:
      - ./web:/ep7-app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    command: sh -c "cd ep7-app && yarn start"
